现网：

hwstaff_pub_servicestagew3/xuyang/xuyang12#$              ID8KU1IGYVNIPPQXBB7G/bQoVG6BLpFw9PeO3I2eeg42TkNVvSYzmoJT10Z3c

hwstaff_pub_csepaasw3/xuyang/xuyang12#$%                 V935VMCYKOQEKUNW1A9N/QdPxHklQsHEkiYERlQ3az0dxKeVfaCnihFa4KEJy

paas_cae_wuzhiheng/wuzhiheng/Huawei#123$

hwstaff_pub_csepaasw3/wuzhiheng/wuzhiheng0..


CAE资源租户：hwstaff_pub_csepaasw3：

上海一：op_svc_cae_40de487942a54a50b4666fa32d11ffa8_cn-east-3/jaoa8QWJAXYD!

北京四：op_svc_cae_40de487942a54a50b4666fa32d11ffa8_cn-north-4/ipm72DYXAZF#

202：op_svc_cae_40de487942a54a50b4666fa32d11ffa8_cn-north-6/vamk11WGBBJE^

广州：op_svc_cae_40de487942a54a50b4666fa32d11ffa8_cn-south-1/zi9d9UBDQK!

-----------------------------------------
hwstaff_pub_servicestagew3：


广州：op_svc_cae_b1dd218393794db892fa784b8e1a0bda_cn-south-1/pqmrcgkIVEYZ#

202：op_svc_cae_b1dd218393794db892fa784b8e1a0bda_cn-north-6/yeysny8c2IEYVW~

上海一：op_svc_cae_b1dd218393794db892fa784b8e1a0bda_cn-east-3/yunjuijeeQYCJUHDEH#

北京四：op_svc_cae_b1dd218393794db892fa784b8e1a0bda_cn-north-4/01ar8kzg4WSJWXNOTL~

---------------------------------------------------
paas_cae_wuzhiheng
上海一：op_svc_cae_a979b7126f38417e9003582c3a608473_cn-east-3/sBwBVsQbtLbP5#

北京四：op_svc_cae_a979b7126f38417e9003582c3a608473_cn-north-4/necxgmsDHXZVO~

广州：op_svc_cae_a979b7126f38417e9003582c3a608473_cn-south-1/vszp3afMIINPFFV~


#############################################


Github:
xygithub2023/xy!7837347    
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

Gitee: 企业版
xuyanggitee_admin/xy!7837347                        
95f39724c4b90dab2b045597773f172b

bitbucket:                           
1437764154@qq.com
xy!7837347

gitlab:
1437764154@qq.com
xy!7837347
zDprZkkFdGoYyoQKRzYc
